import React from "react";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../components/ui/tabs';
import { QuestLog } from '../../components/quests/QuestLog';
import { DailyQuests } from '../../components/quests/DailyQuests';
import { WeeklyQuests } from '../../components/quests/WeeklyQuests';
import { WorldQuests } from '../../components/quests/WorldQuests';
import { HiddenQuests } from '../../components/quests/HiddenQuests';
import { GuildQuests } from '../../components/quests/GuildQuests';
import { CampaignViewer } from '../../components/quests/CampaignViewer';
import { ScrollText, Calendar, TrendingUp, Globe, Eye, Users, BookOpen } from 'lucide-react';
export const QuestsDashboard = () => {
    const [activeTab, setActiveTab] = useState('active');
    return (_jsxs("div", { className: "container mx-auto px-4 py-8", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-4xl font-bold mb-2", children: "Quest Log" }), _jsx("p", { className: "text-gray-400", children: "Track your adventures, complete objectives, and earn rewards" })] }), _jsxs(Tabs, { value: activeTab, onValueChange: setActiveTab, className: "space-y-6", children: [_jsxs(TabsList, { className: "grid w-full grid-cols-7 lg:w-auto", children: [_jsxs(TabsTrigger, { value: "active", className: "flex items-center gap-2", children: [_jsx(ScrollText, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "Active" })] }), _jsxs(TabsTrigger, { value: "daily", className: "flex items-center gap-2", children: [_jsx(Calendar, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "Daily" })] }), _jsxs(TabsTrigger, { value: "weekly", className: "flex items-center gap-2", children: [_jsx(TrendingUp, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "Weekly" })] }), _jsxs(TabsTrigger, { value: "world", className: "flex items-center gap-2", children: [_jsx(Globe, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "World" })] }), _jsxs(TabsTrigger, { value: "hidden", className: "flex items-center gap-2", children: [_jsx(Eye, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "Hidden" })] }), _jsxs(TabsTrigger, { value: "guild", className: "flex items-center gap-2", children: [_jsx(Users, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "Guild" })] }), _jsxs(TabsTrigger, { value: "campaigns", className: "flex items-center gap-2", children: [_jsx(BookOpen, { className: "h-4 w-4" }), _jsx("span", { className: "hidden sm:inline", children: "Campaigns" })] })] }), _jsx(TabsContent, { value: "active", className: "space-y-4", children: _jsx(QuestLog, {}) }), _jsx(TabsContent, { value: "daily", className: "space-y-4", children: _jsx(DailyQuests, {}) }), _jsx(TabsContent, { value: "weekly", className: "space-y-4", children: _jsx(WeeklyQuests, {}) }), _jsx(TabsContent, { value: "world", className: "space-y-4", children: _jsx(WorldQuests, {}) }), _jsx(TabsContent, { value: "hidden", className: "space-y-4", children: _jsx(HiddenQuests, {}) }), _jsx(TabsContent, { value: "guild", className: "space-y-4", children: _jsx(GuildQuests, {}) }), _jsx(TabsContent, { value: "campaigns", className: "space-y-4", children: _jsx(CampaignViewer, {}) })] })] }));
};
