import React from "react";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import StatsDisplay from './StatsDisplay';
import { usePlayer } from '@/hooks/usePlayer';
const ProfileCard = ({ showActions = true }) => {
    const { player, loading } = usePlayer();
    if (loading || !player) {
        return (_jsx(Card, { className: "w-full", children: _jsx(CardContent, { className: "p-6", children: _jsxs("div", { className: "animate-pulse space-y-4", children: [_jsx("div", { className: "h-20 w-20 bg-gray-300 rounded-full" }), _jsx("div", { className: "h-4 bg-gray-300 rounded w-3/4" }), _jsx("div", { className: "h-4 bg-gray-300 rounded w-1/2" })] }) }) }));
    }
    return (_jsxs(Card, { className: "w-full shadow-lg hover:shadow-xl transition-shadow", children: [_jsx(CardHeader, { className: "bg-gradient-to-r from-purple-600 to-indigo-600 text-white", children: _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(Avatar, { className: "h-20 w-20 border-4 border-white", children: _jsx(AvatarFallback, { className: "text-2xl font-bold", children: (player?.username || 'UN').substring(0, 2).toUpperCase() }) }), _jsxs("div", { className: "flex-1", children: [_jsx(CardTitle, { className: "text-2xl", children: player?.username || 'Unknown' }), _jsxs("div", { className: "flex gap-2 mt-2", children: [_jsxs(Badge, { variant: "secondary", children: ["Level ", player?.level || 1] }), _jsx(Badge, { variant: "outline", className: "bg-white/20", children: (player?.moral_class || 'neutral').toUpperCase() }), _jsx(Badge, { variant: "outline", className: "bg-white/20", children: (player?.economic_class || 'middle').toUpperCase() })] })] })] }) }), _jsxs(CardContent, { className: "p-6", children: [_jsx(StatsDisplay, { player: player }), _jsx("div", { className: "mt-6 p-4 bg-gradient-to-r from-yellow-50 to-orange-50 rounded-lg border border-yellow-200", children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "font-semibold text-gray-700", children: "Karma Points" }), _jsx("span", { className: "text-2xl font-bold text-orange-600", children: player?.karma_points || 0 })] }) }), _jsxs("div", { className: "mt-4 grid grid-cols-3 gap-2", children: [_jsxs("div", { className: "p-3 bg-blue-50 rounded-lg text-center", children: [_jsx("div", { className: "text-xs text-gray-600", children: "Credits" }), _jsx("div", { className: "text-lg font-bold text-blue-600", children: player?.currencies?.credits || 0 })] }), _jsxs("div", { className: "p-3 bg-green-50 rounded-lg text-center", children: [_jsx("div", { className: "text-xs text-gray-600", children: "Karma Tokens" }), _jsx("div", { className: "text-lg font-bold text-green-600", children: player?.currencies?.karma_tokens || 0 })] }), _jsxs("div", { className: "p-3 bg-purple-50 rounded-lg text-center", children: [_jsx("div", { className: "text-xs text-gray-600", children: "Dark Matter" }), _jsx("div", { className: "text-lg font-bold text-purple-600", children: player?.currencies?.dark_matter || 0 })] })] })] })] }));
};
export default ProfileCard;
