'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import ModernDashboardLayout from '@/components/ui/layout/sidebar/navigation/items/menu/handlers/ModernDashboardLayout'
import { Plus, Search, Edit, Trash2, Layers } from 'lucide-react'
export default function DSASheetsListPage() {
  const [sheets, setSheets] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const fetch = async () => { try { setLoading(true); const res = await fetch(`/api/admin/dsa/sheets?search=${search}`); const data = await res.json(); setSheets(data.sheets || data.items || []) } catch (e) {} finally { setLoading(false) } }
  useEffect(() => { fetch() }, [search])
  const handleDelete = async (id: string) => { if (!confirm('Delete?')) return; try { await fetch(`/api/admin/dsa/sheets/${id}`, { method: 'DELETE' }); alert('Deleted'); fetch() } catch (e) { alert('Failed') } }
  return <ModernDashboardLayout><div className="space-y-6"><div className="flex items-center justify-between"><div className="flex items-center space-x-3"><div className="p-3 bg-gradient-to-br from-violet-500 to-purple-600 rounded-xl shadow-lg"><Layers className="w-6 h-6 text-white" /></div><div><h1 className="text-3xl font-bold text-slate-900">DSA Sheets</h1></div></div><Link href="/dashboard/dsa/sheets/create"><button className="px-6 py-3 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-lg shadow-lg flex items-center"><Plus className="w-5 h-5 mr-2" />Create</button></Link></div><div className="bg-white rounded-xl shadow-lg border p-6"><div className="relative"><Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-slate-400" /><input type="text" placeholder="Search..." value={search} onChange={(e) => setSearch(e.target.value)} className="w-full pl-11 pr-4 py-3 border rounded-lg focus:ring-2 focus:ring-violet-500" /></div></div><div className="bg-white rounded-xl shadow-lg border overflow-hidden">{loading ? <div className="p-12 text-center"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-violet-600 mx-auto"></div></div> : sheets.length === 0 ? <div className="p-12 text-center"><p>No sheets</p></div> : <table className="w-full"><thead className="bg-slate-50"><tr><th className="px-6 py-4 text-left text-xs font-semibold uppercase">Name</th><th className="px-6 py-4 text-left text-xs font-semibold uppercase">Difficulty</th><th className="px-6 py-4 text-left text-xs font-semibold uppercase">Time</th><th className="px-6 py-4 text-right text-xs font-semibold uppercase">Actions</th></tr></thead><tbody className="divide-y">{sheets.map((s) => <tr key={s._id} className="hover:bg-slate-50"><td className="px-6 py-4 font-semibold">{s.name}</td><td className="px-6 py-4">{s.difficulty}</td><td className="px-6 py-4">{s.estimated_time}</td><td className="px-6 py-4 text-right"><Link href={`/dashboard/dsa/sheets/edit/${s._id}`}><button className="p-2 text-violet-600 hover:bg-violet-50 rounded-lg"><Edit className="w-4 h-4" /></button></Link><button onClick={() => handleDelete(s._id)} className="p-2 text-red-600 hover:bg-red-50 rounded-lg ml-2"><Trash2 className="w-4 h-4" /></button></td></tr>)}</tbody></table>}</div></div></ModernDashboardLayout>
}
